[package]
name = "autoclip"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = "4.5.47"
env_logger = "0.11.8"
ffmpeg-next = "8.0.0"
hound = "3.5.1"
image = "0.25.8"
log = "0.4.28"
opencv = "0.95.1"
serde = "1.0.219"
serde_json = "1.0.143"
tch = "0.20.0"
